spring.application.name=poltrona

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

# Porta
server.port=${PORT:8080}